### ISSUE TITLE
Discord widget

### ISSUE THREAD

**Issue by R3uan3** [Arkrissym/Discord.CPP#7]
Does the lib support displaying members online like this widget:

![brave_2022-10-05_21-58-30](https://user-images.githubusercontent.com/103058225/194191210-b94cb8b7-3103-4f2c-bc1d-068264d5113a.png)

**Comment by Arkrissym** [comment]
As far as i know, to track the online status of guild members you need to process [presence update events](https://discord.com/developers/docs/topics/gateway-events#presence). This lib currently does NOT process them. Due to lack of time i won't implement this myself. However i would recommend to look for other, more complete and better maintained, libraries.

**Comment by R3uan3** [comment]
> However i would recommend to look for other, more complete and better maintained, libraries.

I see, thanks, do you know any other c++ discordlib?

**Comment by Arkrissym** [comment]
Have a look at https://github.com/brainboxdotcc/DPP and https://github.com/yourWaifu/sleepy-discord
